const path = require('path')
const os = require('os')
const dbPath = path.join(process.env.APPDATA, 'ergoflow', 'crm-6da25bf3-0ec6-4e93-8c75-7049dc78e3de.db')
const Database = require(path.join(__dirname, '../node_modules/better-sqlite3'))
const db = new Database(dbPath)
const cats = db.prepare('SELECT id, name_en FROM categories').all()
console.log(JSON.stringify(cats, null, 2))
db.close()
process.exit(0)
