const path = require('path')
const dbPath = path.join(process.env.APPDATA, 'ergoflow', 'crm-6da25bf3-0ec6-4e93-8c75-7049dc78e3de.db')
const Database = require(path.join(__dirname, '../node_modules/better-sqlite3'))
const db = new Database(dbPath)
db.prepare("UPDATE calls SET customer_name = 'James Miller', customer_phone = '+44 7700 900 123' WHERE id = 'fake-call-001'").run()
db.prepare("UPDATE calls SET customer_name = 'Sarah Williams', customer_phone = '+44 7911 123 456' WHERE id = 'fake-call-002'").run()
db.prepare("UPDATE calls SET customer_name = 'Tom Baker', customer_phone = '+44 7800 555 321' WHERE id = 'fake-call-003'").run()
db.prepare("UPDATE calls SET customer_name = 'Emily Clark', customer_phone = '+44 7912 987 654' WHERE id = 'fake-call-004'").run()
console.log('Names updated')
db.close()
process.exit(0)
