-- Add invoice link + totals to jobs, and create job_items table

ALTER TABLE jobs ADD COLUMN IF NOT EXISTS invoice_id TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS subtotal REAL NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS discount_type TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS discount_value REAL NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS discount_amount REAL NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS tax_rate REAL NOT NULL DEFAULT 24;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS tax_amount REAL NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS total REAL NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS job_items (
  id TEXT PRIMARY KEY,
  job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  description TEXT NOT NULL DEFAULT '',
  quantity REAL DEFAULT 1,
  unit_price REAL DEFAULT 0,
  total REAL DEFAULT 0,
  sort_order INTEGER DEFAULT 0,
  synced INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_job_items_job ON job_items(job_id);
